package tensorflow.serving;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prediction_service.proto

public final class PredictionServiceOuterClass {
  private PredictionServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030prediction_service.proto\022\022tensorflow.s" +
      "erving\032\rpredict.proto2g\n\021PredictionServi" +
      "ce\022R\n\007Predict\022\".tensorflow.serving.Predi" +
      "ctRequest\032#.tensorflow.serving.PredictRe" +
      "sponseB\003\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tensorflow.serving.Predict.getDescriptor(),
        }, assigner);
    tensorflow.serving.Predict.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
