// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_attributes.proto

package org.tensorflow.framework;

public interface DeviceAttributesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.DeviceAttributes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Fully specified name of the device within a cluster.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <pre>
   * Fully specified name of the device within a cluster.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * String representation of device_type.
   * </pre>
   *
   * <code>optional string device_type = 2;</code>
   */
  String getDeviceType();
  /**
   * <pre>
   * String representation of device_type.
   * </pre>
   *
   * <code>optional string device_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <pre>
   * Memory capacity of device in bytes.
   * </pre>
   *
   * <code>optional int64 memory_limit = 4;</code>
   */
  long getMemoryLimit();

  /**
   * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
   */
  int getBusAdjacencyValue();
  /**
   * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
   */
  BusAdjacency getBusAdjacency();

  /**
   * <pre>
   * A device is assigned a global unique number each time it is
   * initialized. "incarnation" should never be 0.
   * </pre>
   *
   * <code>optional fixed64 incarnation = 6;</code>
   */
  long getIncarnation();

  /**
   * <pre>
   * String representation of the physical device that this device maps to.
   * </pre>
   *
   * <code>optional string physical_device_desc = 7;</code>
   */
  String getPhysicalDeviceDesc();
  /**
   * <pre>
   * String representation of the physical device that this device maps to.
   * </pre>
   *
   * <code>optional string physical_device_desc = 7;</code>
   */
  com.google.protobuf.ByteString
      getPhysicalDeviceDescBytes();
}
