// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_attributes.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.DeviceAttributes}
 */
public  final class DeviceAttributes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.DeviceAttributes)
    DeviceAttributesOrBuilder {
  // Use DeviceAttributes.newBuilder() to construct.
  private DeviceAttributes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceAttributes() {
    name_ = "";
    deviceType_ = "";
    memoryLimit_ = 0L;
    busAdjacency_ = 0;
    incarnation_ = 0L;
    physicalDeviceDesc_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DeviceAttributes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            deviceType_ = s;
            break;
          }
          case 32: {

            memoryLimit_ = input.readInt64();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            busAdjacency_ = rawValue;
            break;
          }
          case 49: {

            incarnation_ = input.readFixed64();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            physicalDeviceDesc_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.DeviceAttributesProtos.internal_static_tensorflow_DeviceAttributes_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.DeviceAttributesProtos.internal_static_tensorflow_DeviceAttributes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DeviceAttributes.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <pre>
   * Fully specified name of the device within a cluster.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Fully specified name of the device within a cluster.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_TYPE_FIELD_NUMBER = 2;
  private volatile Object deviceType_;
  /**
   * <pre>
   * String representation of device_type.
   * </pre>
   *
   * <code>optional string device_type = 2;</code>
   */
  public String getDeviceType() {
    Object ref = deviceType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * String representation of device_type.
   * </pre>
   *
   * <code>optional string device_type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceTypeBytes() {
    Object ref = deviceType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMORY_LIMIT_FIELD_NUMBER = 4;
  private long memoryLimit_;
  /**
   * <pre>
   * Memory capacity of device in bytes.
   * </pre>
   *
   * <code>optional int64 memory_limit = 4;</code>
   */
  public long getMemoryLimit() {
    return memoryLimit_;
  }

  public static final int BUS_ADJACENCY_FIELD_NUMBER = 5;
  private int busAdjacency_;
  /**
   * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
   */
  public int getBusAdjacencyValue() {
    return busAdjacency_;
  }
  /**
   * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
   */
  public BusAdjacency getBusAdjacency() {
    BusAdjacency result = BusAdjacency.valueOf(busAdjacency_);
    return result == null ? BusAdjacency.UNRECOGNIZED : result;
  }

  public static final int INCARNATION_FIELD_NUMBER = 6;
  private long incarnation_;
  /**
   * <pre>
   * A device is assigned a global unique number each time it is
   * initialized. "incarnation" should never be 0.
   * </pre>
   *
   * <code>optional fixed64 incarnation = 6;</code>
   */
  public long getIncarnation() {
    return incarnation_;
  }

  public static final int PHYSICAL_DEVICE_DESC_FIELD_NUMBER = 7;
  private volatile Object physicalDeviceDesc_;
  /**
   * <pre>
   * String representation of the physical device that this device maps to.
   * </pre>
   *
   * <code>optional string physical_device_desc = 7;</code>
   */
  public String getPhysicalDeviceDesc() {
    Object ref = physicalDeviceDesc_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      physicalDeviceDesc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * String representation of the physical device that this device maps to.
   * </pre>
   *
   * <code>optional string physical_device_desc = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPhysicalDeviceDescBytes() {
    Object ref = physicalDeviceDesc_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      physicalDeviceDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getDeviceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceType_);
    }
    if (memoryLimit_ != 0L) {
      output.writeInt64(4, memoryLimit_);
    }
    if (busAdjacency_ != BusAdjacency.BUS_0.getNumber()) {
      output.writeEnum(5, busAdjacency_);
    }
    if (incarnation_ != 0L) {
      output.writeFixed64(6, incarnation_);
    }
    if (!getPhysicalDeviceDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, physicalDeviceDesc_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getDeviceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceType_);
    }
    if (memoryLimit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, memoryLimit_);
    }
    if (busAdjacency_ != BusAdjacency.BUS_0.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, busAdjacency_);
    }
    if (incarnation_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(6, incarnation_);
    }
    if (!getPhysicalDeviceDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, physicalDeviceDesc_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DeviceAttributes)) {
      return super.equals(obj);
    }
    DeviceAttributes other = (DeviceAttributes) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getDeviceType()
        .equals(other.getDeviceType());
    result = result && (getMemoryLimit()
        == other.getMemoryLimit());
    result = result && busAdjacency_ == other.busAdjacency_;
    result = result && (getIncarnation()
        == other.getIncarnation());
    result = result && getPhysicalDeviceDesc()
        .equals(other.getPhysicalDeviceDesc());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DEVICE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceType().hashCode();
    hash = (37 * hash) + MEMORY_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryLimit());
    hash = (37 * hash) + BUS_ADJACENCY_FIELD_NUMBER;
    hash = (53 * hash) + busAdjacency_;
    hash = (37 * hash) + INCARNATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIncarnation());
    hash = (37 * hash) + PHYSICAL_DEVICE_DESC_FIELD_NUMBER;
    hash = (53 * hash) + getPhysicalDeviceDesc().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DeviceAttributes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DeviceAttributes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DeviceAttributes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DeviceAttributes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DeviceAttributes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DeviceAttributes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DeviceAttributes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DeviceAttributes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DeviceAttributes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DeviceAttributes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DeviceAttributes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.DeviceAttributes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.DeviceAttributes)
      org.tensorflow.framework.DeviceAttributesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.DeviceAttributesProtos.internal_static_tensorflow_DeviceAttributes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.DeviceAttributesProtos.internal_static_tensorflow_DeviceAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceAttributes.class, Builder.class);
    }

    // Construct using org.tensorflow.framework.DeviceAttributes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      deviceType_ = "";

      memoryLimit_ = 0L;

      busAdjacency_ = 0;

      incarnation_ = 0L;

      physicalDeviceDesc_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.DeviceAttributesProtos.internal_static_tensorflow_DeviceAttributes_descriptor;
    }

    public DeviceAttributes getDefaultInstanceForType() {
      return DeviceAttributes.getDefaultInstance();
    }

    public DeviceAttributes build() {
      DeviceAttributes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public DeviceAttributes buildPartial() {
      DeviceAttributes result = new DeviceAttributes(this);
      result.name_ = name_;
      result.deviceType_ = deviceType_;
      result.memoryLimit_ = memoryLimit_;
      result.busAdjacency_ = busAdjacency_;
      result.incarnation_ = incarnation_;
      result.physicalDeviceDesc_ = physicalDeviceDesc_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DeviceAttributes) {
        return mergeFrom((DeviceAttributes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DeviceAttributes other) {
      if (other == DeviceAttributes.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDeviceType().isEmpty()) {
        deviceType_ = other.deviceType_;
        onChanged();
      }
      if (other.getMemoryLimit() != 0L) {
        setMemoryLimit(other.getMemoryLimit());
      }
      if (other.busAdjacency_ != 0) {
        setBusAdjacencyValue(other.getBusAdjacencyValue());
      }
      if (other.getIncarnation() != 0L) {
        setIncarnation(other.getIncarnation());
      }
      if (!other.getPhysicalDeviceDesc().isEmpty()) {
        physicalDeviceDesc_ = other.physicalDeviceDesc_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DeviceAttributes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DeviceAttributes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object name_ = "";
    /**
     * <pre>
     * Fully specified name of the device within a cluster.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Fully specified name of the device within a cluster.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Fully specified name of the device within a cluster.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fully specified name of the device within a cluster.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fully specified name of the device within a cluster.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object deviceType_ = "";
    /**
     * <pre>
     * String representation of device_type.
     * </pre>
     *
     * <code>optional string device_type = 2;</code>
     */
    public String getDeviceType() {
      Object ref = deviceType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * String representation of device_type.
     * </pre>
     *
     * <code>optional string device_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * String representation of device_type.
     * </pre>
     *
     * <code>optional string device_type = 2;</code>
     */
    public Builder setDeviceType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String representation of device_type.
     * </pre>
     *
     * <code>optional string device_type = 2;</code>
     */
    public Builder clearDeviceType() {
      
      deviceType_ = getDefaultInstance().getDeviceType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String representation of device_type.
     * </pre>
     *
     * <code>optional string device_type = 2;</code>
     */
    public Builder setDeviceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceType_ = value;
      onChanged();
      return this;
    }

    private long memoryLimit_ ;
    /**
     * <pre>
     * Memory capacity of device in bytes.
     * </pre>
     *
     * <code>optional int64 memory_limit = 4;</code>
     */
    public long getMemoryLimit() {
      return memoryLimit_;
    }
    /**
     * <pre>
     * Memory capacity of device in bytes.
     * </pre>
     *
     * <code>optional int64 memory_limit = 4;</code>
     */
    public Builder setMemoryLimit(long value) {
      
      memoryLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Memory capacity of device in bytes.
     * </pre>
     *
     * <code>optional int64 memory_limit = 4;</code>
     */
    public Builder clearMemoryLimit() {
      
      memoryLimit_ = 0L;
      onChanged();
      return this;
    }

    private int busAdjacency_ = 0;
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public int getBusAdjacencyValue() {
      return busAdjacency_;
    }
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public Builder setBusAdjacencyValue(int value) {
      busAdjacency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public BusAdjacency getBusAdjacency() {
      BusAdjacency result = BusAdjacency.valueOf(busAdjacency_);
      return result == null ? BusAdjacency.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public Builder setBusAdjacency(BusAdjacency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      busAdjacency_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public Builder clearBusAdjacency() {
      
      busAdjacency_ = 0;
      onChanged();
      return this;
    }

    private long incarnation_ ;
    /**
     * <pre>
     * A device is assigned a global unique number each time it is
     * initialized. "incarnation" should never be 0.
     * </pre>
     *
     * <code>optional fixed64 incarnation = 6;</code>
     */
    public long getIncarnation() {
      return incarnation_;
    }
    /**
     * <pre>
     * A device is assigned a global unique number each time it is
     * initialized. "incarnation" should never be 0.
     * </pre>
     *
     * <code>optional fixed64 incarnation = 6;</code>
     */
    public Builder setIncarnation(long value) {
      
      incarnation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A device is assigned a global unique number each time it is
     * initialized. "incarnation" should never be 0.
     * </pre>
     *
     * <code>optional fixed64 incarnation = 6;</code>
     */
    public Builder clearIncarnation() {
      
      incarnation_ = 0L;
      onChanged();
      return this;
    }

    private Object physicalDeviceDesc_ = "";
    /**
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     *
     * <code>optional string physical_device_desc = 7;</code>
     */
    public String getPhysicalDeviceDesc() {
      Object ref = physicalDeviceDesc_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        physicalDeviceDesc_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     *
     * <code>optional string physical_device_desc = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPhysicalDeviceDescBytes() {
      Object ref = physicalDeviceDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        physicalDeviceDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     *
     * <code>optional string physical_device_desc = 7;</code>
     */
    public Builder setPhysicalDeviceDesc(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      physicalDeviceDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     *
     * <code>optional string physical_device_desc = 7;</code>
     */
    public Builder clearPhysicalDeviceDesc() {
      
      physicalDeviceDesc_ = getDefaultInstance().getPhysicalDeviceDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     *
     * <code>optional string physical_device_desc = 7;</code>
     */
    public Builder setPhysicalDeviceDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      physicalDeviceDesc_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.DeviceAttributes)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.DeviceAttributes)
  private static final DeviceAttributes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DeviceAttributes();
  }

  public static DeviceAttributes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceAttributes>
      PARSER = new com.google.protobuf.AbstractParser<DeviceAttributes>() {
    public DeviceAttributes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceAttributes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceAttributes> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DeviceAttributes> getParserForType() {
    return PARSER;
  }

  public DeviceAttributes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

